service: ats-integration-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  environment:
    ATS_API_KEY: ${env:ATS_API_KEY, 'headers-api-key-placeholder'}
    ATS_BASE_URL: ${env:ATS_BASE_URL, 'https://harvest.greenhouse.io/v1'}
    ON_BEHALF_OF: ${env:ON_BEHALF_OF, ''}

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  getJobs:
    handler: handler.get_jobs
    events:
      - http:
          path: jobs
          method: get
          cors: true

  createCandidate:
    handler: handler.create_candidate
    events:
      - http:
          path: candidates
          method: post
          cors: true

  getApplications:
    handler: handler.get_applications
    events:
      - http:
          path: applications
          method: get
          cors: true
